/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NaacRouteImport } from './routes/naac'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as InstitutionsSlugRouteImport } from './routes/institutions.$slug'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NaacRoute = NaacRouteImport.update({
  id: '/naac',
  path: '/naac',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsSlugRoute = InstitutionsSlugRouteImport.update({
  id: '/institutions/$slug',
  path: '/institutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/institutions/': typeof InstitutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/institutions': typeof InstitutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/institutions/': typeof InstitutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/institutions/$slug'
    | '/institutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/institutions/$slug'
    | '/institutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/institutions/$slug'
    | '/institutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DisclosuresRoute: typeof DisclosuresRoute
  GalleryRoute: typeof GalleryRoute
  NaacRoute: typeof NaacRoute
  NewsRoute: typeof NewsRoute
  InstitutionsSlugRoute: typeof InstitutionsSlugRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naac': {
      id: '/naac'
      path: '/naac'
      fullPath: '/naac'
      preLoaderRoute: typeof NaacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$slug': {
      id: '/institutions/$slug'
      path: '/institutions/$slug'
      fullPath: '/institutions/$slug'
      preLoaderRoute: typeof InstitutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionsRoute: AdmissionsRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DisclosuresRoute: DisclosuresRoute,
  GalleryRoute: GalleryRoute,
  NaacRoute: NaacRoute,
  NewsRoute: NewsRoute,
  InstitutionsSlugRoute: InstitutionsSlugRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
