/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NaacRouteImport } from './routes/naac'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtadminRouteImport } from './routes/@admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as AtadminIndexRouteImport } from './routes/@admin.index'
import { Route as InstitutionsSlugRouteImport } from './routes/institutions.$slug'
import { Route as AtadminProfileRouteImport } from './routes/@admin.profile'
import { Route as AtadminForgotPasswordRouteImport } from './routes/@admin.forgot-password'
import { Route as AtadminDashboardRouteImport } from './routes/@admin.dashboard'
import { Route as AtadminCampusesIndexRouteImport } from './routes/@admin.campuses.index'
import { Route as AtadminCampusesCreateRouteImport } from './routes/@admin.campuses.create'
import { Route as AtadminCampusesIdRouteImport } from './routes/@admin.campuses.$id'
import { Route as AtadminCampusesIdEditRouteImport } from './routes/@admin.campuses.$id.edit'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NaacRoute = NaacRouteImport.update({
  id: '/naac',
  path: '/naac',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtadminRoute = AtadminRouteImport.update({
  id: '/@admin',
  path: '/@admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtadminIndexRoute = AtadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtadminRoute,
} as any)
const InstitutionsSlugRoute = InstitutionsSlugRouteImport.update({
  id: '/institutions/$slug',
  path: '/institutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtadminProfileRoute = AtadminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminForgotPasswordRoute = AtadminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminDashboardRoute = AtadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminCampusesIndexRoute = AtadminCampusesIndexRouteImport.update({
  id: '/campuses/',
  path: '/campuses/',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminCampusesCreateRoute = AtadminCampusesCreateRouteImport.update({
  id: '/campuses/create',
  path: '/campuses/create',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminCampusesIdRoute = AtadminCampusesIdRouteImport.update({
  id: '/campuses/$id',
  path: '/campuses/$id',
  getParentRoute: () => AtadminRoute,
} as any)
const AtadminCampusesIdEditRoute = AtadminCampusesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AtadminCampusesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@admin': typeof AtadminRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/@admin/dashboard': typeof AtadminDashboardRoute
  '/@admin/forgot-password': typeof AtadminForgotPasswordRoute
  '/@admin/profile': typeof AtadminProfileRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/@admin/': typeof AtadminIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/@admin/campuses/$id': typeof AtadminCampusesIdRouteWithChildren
  '/@admin/campuses/create': typeof AtadminCampusesCreateRoute
  '/@admin/campuses/': typeof AtadminCampusesIndexRoute
  '/@admin/campuses/$id/edit': typeof AtadminCampusesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/@admin/dashboard': typeof AtadminDashboardRoute
  '/@admin/forgot-password': typeof AtadminForgotPasswordRoute
  '/@admin/profile': typeof AtadminProfileRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/@admin': typeof AtadminIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/@admin/campuses/$id': typeof AtadminCampusesIdRouteWithChildren
  '/@admin/campuses/create': typeof AtadminCampusesCreateRoute
  '/@admin/campuses': typeof AtadminCampusesIndexRoute
  '/@admin/campuses/$id/edit': typeof AtadminCampusesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@admin': typeof AtadminRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/disclosures': typeof DisclosuresRoute
  '/gallery': typeof GalleryRoute
  '/naac': typeof NaacRoute
  '/news': typeof NewsRoute
  '/@admin/dashboard': typeof AtadminDashboardRoute
  '/@admin/forgot-password': typeof AtadminForgotPasswordRoute
  '/@admin/profile': typeof AtadminProfileRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
  '/@admin/': typeof AtadminIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/@admin/campuses/$id': typeof AtadminCampusesIdRouteWithChildren
  '/@admin/campuses/create': typeof AtadminCampusesCreateRoute
  '/@admin/campuses/': typeof AtadminCampusesIndexRoute
  '/@admin/campuses/$id/edit': typeof AtadminCampusesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@admin'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/@admin/dashboard'
    | '/@admin/forgot-password'
    | '/@admin/profile'
    | '/institutions/$slug'
    | '/@admin/'
    | '/institutions/'
    | '/@admin/campuses/$id'
    | '/@admin/campuses/create'
    | '/@admin/campuses/'
    | '/@admin/campuses/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/@admin/dashboard'
    | '/@admin/forgot-password'
    | '/@admin/profile'
    | '/institutions/$slug'
    | '/@admin'
    | '/institutions'
    | '/@admin/campuses/$id'
    | '/@admin/campuses/create'
    | '/@admin/campuses'
    | '/@admin/campuses/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/@admin'
    | '/about'
    | '/achievements'
    | '/admissions'
    | '/career'
    | '/contact'
    | '/courses'
    | '/disclosures'
    | '/gallery'
    | '/naac'
    | '/news'
    | '/@admin/dashboard'
    | '/@admin/forgot-password'
    | '/@admin/profile'
    | '/institutions/$slug'
    | '/@admin/'
    | '/institutions/'
    | '/@admin/campuses/$id'
    | '/@admin/campuses/create'
    | '/@admin/campuses/'
    | '/@admin/campuses/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtadminRoute: typeof AtadminRouteWithChildren
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DisclosuresRoute: typeof DisclosuresRoute
  GalleryRoute: typeof GalleryRoute
  NaacRoute: typeof NaacRoute
  NewsRoute: typeof NewsRoute
  InstitutionsSlugRoute: typeof InstitutionsSlugRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naac': {
      id: '/naac'
      path: '/naac'
      fullPath: '/naac'
      preLoaderRoute: typeof NaacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@admin': {
      id: '/@admin'
      path: '/@admin'
      fullPath: '/@admin'
      preLoaderRoute: typeof AtadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@admin/': {
      id: '/@admin/'
      path: '/'
      fullPath: '/@admin/'
      preLoaderRoute: typeof AtadminIndexRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/institutions/$slug': {
      id: '/institutions/$slug'
      path: '/institutions/$slug'
      fullPath: '/institutions/$slug'
      preLoaderRoute: typeof InstitutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@admin/profile': {
      id: '/@admin/profile'
      path: '/profile'
      fullPath: '/@admin/profile'
      preLoaderRoute: typeof AtadminProfileRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/forgot-password': {
      id: '/@admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/@admin/forgot-password'
      preLoaderRoute: typeof AtadminForgotPasswordRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/dashboard': {
      id: '/@admin/dashboard'
      path: '/dashboard'
      fullPath: '/@admin/dashboard'
      preLoaderRoute: typeof AtadminDashboardRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/campuses/': {
      id: '/@admin/campuses/'
      path: '/campuses'
      fullPath: '/@admin/campuses/'
      preLoaderRoute: typeof AtadminCampusesIndexRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/campuses/create': {
      id: '/@admin/campuses/create'
      path: '/campuses/create'
      fullPath: '/@admin/campuses/create'
      preLoaderRoute: typeof AtadminCampusesCreateRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/campuses/$id': {
      id: '/@admin/campuses/$id'
      path: '/campuses/$id'
      fullPath: '/@admin/campuses/$id'
      preLoaderRoute: typeof AtadminCampusesIdRouteImport
      parentRoute: typeof AtadminRoute
    }
    '/@admin/campuses/$id/edit': {
      id: '/@admin/campuses/$id/edit'
      path: '/edit'
      fullPath: '/@admin/campuses/$id/edit'
      preLoaderRoute: typeof AtadminCampusesIdEditRouteImport
      parentRoute: typeof AtadminCampusesIdRoute
    }
  }
}

interface AtadminCampusesIdRouteChildren {
  AtadminCampusesIdEditRoute: typeof AtadminCampusesIdEditRoute
}

const AtadminCampusesIdRouteChildren: AtadminCampusesIdRouteChildren = {
  AtadminCampusesIdEditRoute: AtadminCampusesIdEditRoute,
}

const AtadminCampusesIdRouteWithChildren =
  AtadminCampusesIdRoute._addFileChildren(AtadminCampusesIdRouteChildren)

interface AtadminRouteChildren {
  AtadminDashboardRoute: typeof AtadminDashboardRoute
  AtadminForgotPasswordRoute: typeof AtadminForgotPasswordRoute
  AtadminProfileRoute: typeof AtadminProfileRoute
  AtadminIndexRoute: typeof AtadminIndexRoute
  AtadminCampusesIdRoute: typeof AtadminCampusesIdRouteWithChildren
  AtadminCampusesCreateRoute: typeof AtadminCampusesCreateRoute
  AtadminCampusesIndexRoute: typeof AtadminCampusesIndexRoute
}

const AtadminRouteChildren: AtadminRouteChildren = {
  AtadminDashboardRoute: AtadminDashboardRoute,
  AtadminForgotPasswordRoute: AtadminForgotPasswordRoute,
  AtadminProfileRoute: AtadminProfileRoute,
  AtadminIndexRoute: AtadminIndexRoute,
  AtadminCampusesIdRoute: AtadminCampusesIdRouteWithChildren,
  AtadminCampusesCreateRoute: AtadminCampusesCreateRoute,
  AtadminCampusesIndexRoute: AtadminCampusesIndexRoute,
}

const AtadminRouteWithChildren =
  AtadminRoute._addFileChildren(AtadminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtadminRoute: AtadminRouteWithChildren,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionsRoute: AdmissionsRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DisclosuresRoute: DisclosuresRoute,
  GalleryRoute: GalleryRoute,
  NaacRoute: NaacRoute,
  NewsRoute: NewsRoute,
  InstitutionsSlugRoute: InstitutionsSlugRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
